### ISSUE TITLE
本地启动中，auth服务和system服务问题

### ISSUE THREAD

**Issue by jiechen257** [youlaitech/youlai-mall#101]
auth服务中，微信appid匹配不上：
![image](https://user-images.githubusercontent.com/73946940/225810067-4c2c39c7-cc35-448f-81d9-b5291f24bec3.png)

system服务中，knife4j的password：
![image](https://user-images.githubusercontent.com/73946940/225810151-f87d27d1-b2ef-4a3a-958a-e7e685664711.png)

**Comment by hxrui** [comment]
@jiechen257 这不是不匹配的问题，是你应用根本没连接到nacos配置中心

**Comment by jiechen257** [comment]
> 

thanks
