### ISSUE TITLE
登录时报403错误

### ISSUE THREAD

**Issue by wangtaocs** [youlaitech/youlai-mall#102]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/60781124/233786338-8abfc994-bf78-4924-a374-8542ea036059.png">

**Comment by hxrui** [comment]
@wangtaocs 操作系统截图

**Comment by wangtaocs** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/60781124/233788129-31df0725-5163-4cf2-a623-b1532d954777.png">
这个可以吗

**Comment by springboot4** [comment]
![](https://cdn.staticaly.com/gh/fxzbiz/img@url/2023/04/24/rtm6Cr.png)
![](https://cdn.staticaly.com/gh/fxzbiz/img@url/2023/04/24/Il9Ys1.png)

**Comment by springboot4** [comment]
> <img alt="图像" width="280" src="https://user-images.githubusercontent.com/60781124/233788129-31df0725-5163-4cf2-a623-b1532d954777.png">
> 
> 这个可以吗

同mac系统。未能复现你说的问题。如果你那边还存在此问题可以加我微信 远程给你看一下。vx: fxz_0127

**Comment by kcaco2000** [comment]
这个问题解决了吗，同mac也遇到了这个问题

**Comment by wangtaocs** [comment]
> 这个问题解决了吗，同mac也遇到了这个问题

已解决，请关闭本地的VPN
