### ISSUE TITLE
请问gateWay中AuthorizationManager这个类中roleId怎么来的。

### ISSUE THREAD

**Issue by yqx868** [youlaitech/youlai-mall#11]
我把某些注释掉了就走到下面 

Mono<AuthorizationDecision> authorizationDecisionMono = mono
                .filter(Authentication::isAuthenticated)
                .flatMapIterable(Authentication::getAuthorities)
                .map(GrantedAuthority::getAuthority)
                .any(roleId -> {
                    // roleId是请求用户的角色(格式:ROLE_{roleId})，authorities是请求资源所需要角色的集合
                    log.info("访问路径：{}", path);
                    log.info("用户角色信息：{}", roleId);
                    log.info("资源需要权限authorities：{}", authorities);
                    return authorities.contains(roleId);
                })
                .map(AuthorizationDecision::new)
                .defaultIfEmpty(new AuthorizationDecision(false));

**Comment by hxrui** [comment]
角色roleId是JWT的载体部分的authorities
![image](https://user-images.githubusercontent.com/12759477/104309294-e1ba8d00-550c-11eb-9104-07cf0d852641.png)

**Comment by hyq965672903** [comment]
@Bean
    public TokenEnhancer tokenEnhancer() {
        return (accessToken, authentication) -> {
            Map<String, Object> map = new HashMap<>(2);
            User user = (User) authentication.getUserAuthentication().getPrincipal();
            map.put(AuthConstants.JWT_USER_ID_KEY, user.getId());
            map.put(AuthConstants.JWT_CLIENT_ID_KEY, user.getClientId());
            ((DefaultOAuth2AccessToken) accessToken).setAdditionalInformation(map);
            return accessToken;
        };
    }

**Comment by hyq965672903** [comment]
JWT内容增强 内容增强 并没有增加角色数据进去啊
