### ISSUE TITLE
gateway对外内存溢出

### ISSUE THREAD

**Issue by 15868153548** [youlaitech/youlai-mall#13]
有出现过gateway堆外内存溢出的情况吗？
io.netty.handler.codec.EncoderException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 855638023, max: 872415232)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$OAuth2ResourceServerSpec$BearerTokenAuthenticationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]

**Comment by hxrui** [comment]
没有遇到过这种堆外内存溢出的情况，这种是经过多久时间飙到这么高的内存？

**Comment by hxrui** [comment]
@15868153548
没有遇到过这种堆外内存溢出的情况，这种是经过多久时间飙到这么高的内存？

**Comment by 15868153548** [comment]
一台4G机器，跑了两天吧，流量也不是很大

**Comment by hxrui** [comment]
@15868153548 演示环境2G机器，一直在跑好几月了没啥问题，可能是依赖版本问题

**Comment by dy520qy0326** [comment]
<spring-boot.version>2.3.2.RELEASE</spring-boot.version>
<spring-cloud-alibaba.version>2.2.5.RELEASE</spring-cloud-alibaba.version>
<spring-cloud.version>Hoxton.SR9</spring-cloud.version>
我自己的项目在如上版本下不会出现内存泄露的问题，某些版本请求数量累计值升高以后会出现，和netty版本有关

**Comment by hxrui** [comment]
@dy520qy0326 👍🏻

**Comment by 15868153548** [comment]
> <spring-boot.version>2.3.2.RELEASE</spring-boot.version>
> <spring-cloud-alibaba.version>2.2.5.RELEASE</spring-cloud-alibaba.version>
> <spring-cloud.version>Hoxton.SR9</spring-cloud.version>
> 我自己的项目在如上版本下不会出现内存泄露的问题，某些版本请求数量累计值升高以后会出现，和netty版本有关

请问你的netty版本是多少

**Comment by dy520qy0326** [comment]
> > <spring-boot.version>2.3.2.RELEASE</spring-boot.version>
> > <spring-cloud-alibaba.version>2.2.5.RELEASE</spring-cloud-alibaba.version>
> > <spring-cloud.version>Hoxton.SR9</spring-cloud.version>
> > 我自己的项目在如上版本下不会出现内存泄露的问题，某些版本请求数量累计值升高以后会出现，和netty版本有关
> 
> 请问你的netty版本是多少 
才看到 网关的netty版本如下
<groupId>io.netty</groupId>
<artifactId>netty-all</artifactId>
<version>4.1.51.Final</version>
