### ISSUE TITLE
提问：关于资源服务器的定位问题

### ISSUE THREAD

**Issue by shanzhaozhen** [youlaitech/youlai-mall#2]
看到网上的实例对资源的鉴权主要分两种，一种是将gateway作为资源管理器，其他服务之间调用不需要安全认证直接访问（这正是该项目的做法），另一种是每个微服务都加入资源服务器配置，实现处处认证。感觉这两种方案好像都不太实际，有咩有更好的方案呢。

**Comment by hxrui** [comment]
每个微服务都加入资源服务器的配置太冗余了，可以限制用户直接访问到微服务，必须通过网关访问。https://blog.csdn.net/Hpsyche/article/details/102926010

**Comment by shanzhaozhen** [comment]
也是，但是这样子就做不到服务之间的权限限制了，我是在想这个问题。虽然安全方面上可以在服务器上限制仅哪些ip可以访问

**Comment by hxrui** [comment]
应该没必要担心微服务之间的相互调用权限的问题，毕竟请求到微服务都会走过一趟网关了，经过鉴权后的微服务在再调用另一个微服务说的过去

**Comment by shanzhaozhen** [comment]
> 应该没必要担心微服务之间的相互调用权限的问题，毕竟请求到微服务都会走过一趟网关了，经过鉴权后的微服务在再调用另一个微服务说的过去
还有一个小问题，资源权限角色缓存在redis里面的信息是不是还没做动态更新，假如修改了资源角色关系的话，是不是应该更新一下缓存呢

**Comment by hxrui** [comment]
是的，应该要更新redis的缓存，这边因为目前着手几个端开发就自己一个人，时间有限，所以暂目前没做

**Comment by shanzhaozhen** [comment]
> 是的，应该要更新redis的缓存，这边因为目前着手几个端开发就自己一个人，时间有限，所以暂目前没做

那我觉得没必要做成启动加载，做成接口缓存更好吧

**Comment by hxrui** [comment]
这个没必要暴露出来手动刷新吧

**Comment by gzymomo** [comment]
> 每个微服务都加入资源服务器的配置太冗余了，可以限制用户直接访问到微服务，必须通过网关访问。https://blog.csdn.net/Hpsyche/article/details/102926010

随着项目的发展 网关会成为瓶颈

**Comment by abcdelf** [comment]
> > 每个微服务都加入资源服务器的配置太冗余了，可以限制用户直接访问到微服务，必须通过网关访问。https://blog.csdn.net/Hpsyche/article/details/102926010
> 
> 随着项目的发展 网关会成为瓶颈

网关做一下集群不久可以了吗，

**Comment by lm-lan** [comment]
为啥，又变成每个资源服务器单独认证了
