### ISSUE TITLE
网关的RedisGatewayConfig拼写错了，少了个a

### ISSUE THREAD

**Issue by gadfly3173** [youlaitech/youlai-mall#30]
https://github.com/hxrui/youlai-mall/blob/bff37cda62dd6796a1b6f8f673dc9721cfcc2507/youlai-gateway/src/main/java/com/youlai/gateway/config/RedisGatewyConfig.java#L11-L16

**Comment by hxrui** [comment]
收到，谢谢

**Comment by gadfly3173** [comment]
补充：PAID是薪水的意思，已支付应该是PAYED
https://github.com/hxrui/youlai-mall/blob/bff37cda62dd6796a1b6f8f673dc9721cfcc2507/mall-oms/oms-api/src/main/java/com/youlai/mall/oms/enums/OrderStatusEnum.java#L19

**Comment by gadfly3173** [comment]
补充：docs中给出的配置文件`youlai-gateway.yaml`，白名单只配置了`/youlai-auth/oauth/token`，对于小程序登录是会失效的，需要再加上`/youlai-auth/oauth/token/**`
