### ISSUE TITLE
关于seata配置

### ISSUE THREAD

**Issue by gadfly3173** [youlaitech/youlai-mall#31]
docs里只有Default和Sentinel分组的nacos配置，但是`mall-pms.yaml`里面又有seata的配置，用到了SEATA_GROUP和service.vgroupMapping.mall_tx_group。代码中似乎没有给出这些配置的内容

**Comment by hxrui** [comment]
@gadfly3173 在这篇项目文档对配置出处有说明  https://www.cnblogs.com/haoxianrui/p/14280184.html
