### ISSUE TITLE
[讨论]关于小程序不支持PATCH请求的处理

### ISSUE THREAD

**Issue by gadfly3173** [youlaitech/youlai-mall#37]
小程序官方说明是不支持PATCH操作的，我现在的解决方案是用axios拦截器，将patch请求转为post，并在header中加上`X-Http-Method: PATCH`。
然后再在SecurityGlobalFilter里读取这个header，重新包装成patch请求。线上的话可以考虑换成nginx等进行处理。大佬们有没有更好的处理方法呢

**Comment by hxrui** [comment]
@gadfly3173 个人建议觉得没必要这么繁琐了，既然小程序代理转发中没有PATCH，开发的时候前后端协商使用其他方式代替这种局部更新

**Comment by gadfly3173** [comment]
@hxrui 主要是为了尽量不改动现有接口的情况下让功能跑通。比如现在购物车的全选接口就是走的patch
