### ISSUE TITLE
登錄密碼隱藏

### ISSUE THREAD

**Issue by GuoHM** [youlaitech/youlai-mall#46]
在使用oauth密碼模式驗證的時候會直接將密碼明文暴露在request param裏面，請問有什麽好的優化方法嗎

![image](https://user-images.githubusercontent.com/28671797/128807707-c063ea0e-5e4b-47ad-bc1f-ef358e718c79.png)

**Comment by hxrui** [comment]
@GuoHM 使用https传输URL上的参数都是加密的，其实担心所谓的安全就是在传输过程中用户名和密码信息被窃取

**Comment by GuoHM** [comment]
> @GuoHM 使用https传输URL上的参数都是加密的，其实担心所谓的安全就是在传输过程中用户名和密码信息被窃取

也就是說在https環境下是可以這樣子直接傳輸密碼明文的嗎

**Comment by hxrui** [comment]
@GuoHM 嗯 从数据传输过程中被窃取的角度考虑安全问题使用https是无需担心的

**Comment by GuoHM** [comment]
> @GuoHM 嗯 从数据传输过程中被窃取的角度考虑安全问题使用https是无需担心的
好的謝謝

我還有一個問題，代碼中client_id和client_secret放在header的authorization裏面，具體在代碼哪個地方實現這個功能呢
![image](https://user-images.githubusercontent.com/28671797/128813029-b9d542fe-23ae-4ed7-a4d2-7f7730adcc4a.png)

**Comment by gadfly3173** [comment]
> 
> 我還有一個問題，代碼中client_id和client_secret放在header的authorization裏面，具體在代碼哪個地方實現這個功能呢

前端在header里加上就行，用拦截器或者你手动每个请求加什么的都是随你的

**Comment by gadfly3173** [comment]
> 什么时候https能加密url了？

>## What information does HTTPS protect?
>HTTPS encrypts nearly all information sent between a client and a web service.
>
>For example, an **unencrypted HTTP** request reveals not just the body of the request, but the full URL, query string, and various HTTP headers about the client and request:
>
>![image](https://user-images.githubusercontent.com/28685179/137418654-33ac827d-5a45-440a-a6a3-bafee37507b7.png)
>
>An **encrypted HTTPS** request protects most things:
>
>![image](https://user-images.githubusercontent.com/28685179/137418659-e71ca608-873d-4f45-a6c4-934b5ad8b7aa.png)
>
>This is the same for all HTTP methods (GET, POST, PUT, etc.). The URL path and query string parameters are encrypted, as are POST bodies.

refer: [https://https.cio.gov/faq/](https://https.cio.gov/faq/)

**Comment by tshwangq** [comment]
> > 什么时候https能加密url了？
> 
> > ## What information does HTTPS protect?
> > HTTPS encrypts nearly all information sent between a client and a web service.
> > For example, an **unencrypted HTTP** request reveals not just the body of the request, but the full URL, query string, and various HTTP headers about the client and request:
> > ![image](https://user-images.githubusercontent.com/28685179/137418654-33ac827d-5a45-440a-a6a3-bafee37507b7.png)
> > An **encrypted HTTPS** request protects most things:
> > ![image](https://user-images.githubusercontent.com/28685179/137418659-e71ca608-873d-4f45-a6c4-934b5ad8b7aa.png)
> > This is the same for all HTTP methods (GET, POST, PUT, etc.). The URL path and query string parameters are encrypted, as are POST bodies.
> 
> refer: https://https.cio.gov/faq/

看来我一直理解错误
