### ISSUE TITLE
swagger地址怎么访问

### ISSUE THREAD

**Issue by flyme6** [youlaitech/youlai-mall#6]

**Comment by hxrui** [comment]
http:// localhost:8000/doc.html

**Comment by snoopy-chxy** [comment]
swagger访问页面空白的，看日志有些报错

**Comment by hxrui** [comment]
> swagger访问页面空白的，看日志有些报错

![](https://raw.githubusercontent.com/hxrui/image/main/image/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20201230110724.png)

看地址栏
