### ISSUE TITLE
它们在业务中的使用场景是怎么样的呢？不安装有什么影响么？

### ISSUE THREAD

**Issue by wjzhangcsu** [youlaitech/youlai-mall#77]
RabbitMQ 消息队列
Seata  分布式事务
Sentinel 熔断限流

**Comment by hxrui** [comment]
@wjzhangcsu 非必装是可以使用有来线上的环境，必装的mysql和redis因为怕修改了线上数据导致冲突，使用场景可以看博客都有介绍，博客地址：https://www.cnblogs.com/haoxianrui/
![image](https://user-images.githubusercontent.com/12759477/152900107-357b248c-97be-4268-a3f2-fbaa98d5f7e3.png)
