### ISSUE TITLE
请问如何获取登陆用户的信息? 例如像(Pig)其他开源的项目拥有SecurityUtils

### ISSUE THREAD

**Issue by rougeyan** [youlaitech/youlai-mall#80]
@UtilityClass
public class SecurityUtils {

	/**
	 * 获取Authentication
	 */
	public Authentication getAuthentication() {
		return SecurityContextHolder.getContext().getAuthentication();
	}

	/**
	 * 获取用户
	 */
	public PigUser getUser(Authentication authentication) {
		Object principal = authentication.getPrincipal();
		if (principal instanceof PigUser) {
			return (PigUser) principal;
		}
		return null;
	}

**Comment by hxrui** [comment]
@rougeyan [UserUtils#getUserId()](https://github.com/youlaitech/youlai-mall/blob/master/youlai-common/common-web/src/main/java/com/youlai/common/web/util/UserUtils.java)
