### ISSUE TITLE
bug:There is no client authentication

### ISSUE THREAD

**Issue by acfly** [youlaitech/youlai-mall#94]
`@PostMapping("/token")
    public Object postAccessToken(
            @ApiIgnore Principal principal,
            @ApiIgnore @RequestParam Map<String, String> parameters
    ) throws HttpRequestMethodNotSupportedException {

        /**
         * 获取登录认证的客户端ID
         *
         * 兼容两种方式获取Oauth2客户端信息（client_id、client_secret）
         * 方式一：client_id、client_secret放在请求路径中(注：当前版本已废弃)
         * 方式二：放在请求头（Request Headers）中的Authorization字段，且经过加密，例如 Basic Y2xpZW50OnNlY3JldA== 明文等于 client:secret
         */
        String clientId = RequestUtils.getOAuth2ClientId();
        log.info("OAuth认证授权 客户端ID:{}，请求参数：{}", clientId, JSONUtil.toJsonStr(parameters));

        /**
         * 构造principal
         */

        /**
         * knife4j接口文档测试使用
         *
         * 请求头自动填充，token必须原生返回，不能有任何包装，否则显示 undefined undefined
         * 账号/密码:  client_id/client_secret : client/123456
         */
        if (SecurityConstants.TEST_CLIENT_ID.equals(clientId)) {
            return tokenEndpoint.postAccessToken(principal, parameters).getBody();
        }

        OAuth2AccessToken accessToken = tokenEndpoint.postAccessToken(principal, parameters).getBody();
        return Result.success(accessToken);
    }
`

principal is always null, and postAccessToken function throw exception. we get 

`{
    "code": "B0001",
    "data": null,
    "msg": "There is no client authentication. Try adding an appropriate authentication filter."
}`

**Comment by hxrui** [comment]
@acfly Show your request parameters, preferably cURL.

**Comment by hxrui** [comment]
Please check the source code you have changed
![image](https://user-images.githubusercontent.com/12759477/187941491-1242b751-01b2-4617-9b02-59e7ddf4ab24.png)

**Comment by acfly** [comment]
thanks for your quick reply.

it turns ok after changing  springboot version from 2.6.8 to 2.7.0. but I am not sure.  
and remove "/oauth/**" not work.
